name: Build My Application

on: push

jobs:
  build:
    # Job name is "Build our App"
    name: Build our App
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v2
      - name: Print Current Directory
        run: pwd
      - name: List Filed in Directory
        run: ls
